import { FieldType } from "@/@types/index.type";
import {
  CAR_BRAND_OPTIONS,
  CAR_TRANSMISSION_OPTIONS,
  CAR_CONDITION_OPTIONS,
  CAR_COLOR_OPTIONS,
  CAR_MODEL_OPTIONS,
  CAR_FUELTYPE_OPTIONS,
  CAR_BODY_TYPE_OPTIONS,
  CAR_KEY_FEATURES_OPTIONS,
  CAR_DRIVETRAIN_OPTIONS,
} from "./car-options";

export const addRentalFields: FieldType[] = [
  {
    name: "brand",
    fieldType: "select",
    label: "Marque",
    required: true,
    disabled: false,
    options: CAR_BRAND_OPTIONS,
  },
  {
    name: "model",
    fieldType: "select",
    label: "Modèle",
    required: true,
    disabled: false,
    options: CAR_MODEL_OPTIONS,
  },
  {
    name: "exteriorColor",
    fieldType: "select",
    label: "Couleur extérieure",
    required: true,
    disabled: false,
    options: CAR_COLOR_OPTIONS,
  },
  {
    name: "interiorColor",
    fieldType: "select",
    label: "Couleur intérieure",
    required: false,
    disabled: false,
    options: CAR_COLOR_OPTIONS,
  },
  {
    name: "condition",
    fieldType: "select",
    label: "État",
    required: true,
    disabled: false,
    options: CAR_CONDITION_OPTIONS,
  },
  {
    name: "currentMileage",
    fieldType: "number",
    label: "Kilométrage actuel",
    required: false,
    disabled: false,
  },
  {
    name: "transmission",
    fieldType: "select",
    label: "Transmission",
    required: false,
    disabled: false,
    options: CAR_TRANSMISSION_OPTIONS,
  },
  {
    name: "fuelType",
    fieldType: "select",
    label: "Type de carburant",
    required: true,
    disabled: false,
    options: CAR_FUELTYPE_OPTIONS,
  },
  {
    name: "keyFeatures",
    fieldType: "multiselect",
    label: "Caractéristiques",
    required: false,
    disabled: false,
    options: CAR_KEY_FEATURES_OPTIONS,
  },
  {
    name: "bodyType",
    fieldType: "select",
    label: "Type de carrosserie",
    required: false,
    disabled: false,
    options: CAR_BODY_TYPE_OPTIONS,
  },
  {
    name: "drivetrain",
    fieldType: "select",
    label: "Transmission",
    required: true,
    disabled: false,
    options: CAR_DRIVETRAIN_OPTIONS,
  },
  {
    name: "seatingCapacity",
    fieldType: "number",
    label: "Capacité de places",
    required: false,
    disabled: false,
  },
  {
    name: "description",
    fieldType: "textarea",
    label: "Description",
    col: 2,
    required: false,
    disabled: false,
  },
  {
    name: "dailyRentalPrice",
    fieldType: "currency",
    label: "Prix de location journalier (Ar)",
    col: 1,
    required: true,
    disabled: false,
  },
  {
    name: "minimumRentalDays",
    fieldType: "number",
    label: "Jours de location minimum",
    col: 1,
    required: false,
    disabled: false,
  },
  {
    name: "depositAmount",
    fieldType: "currency",
    label: "Montant de la caution (Ar)",
    col: 1,
    required: false,
    disabled: false,
  },
  {
    name: "rentalStatus",
    fieldType: "select",
    label: "Statut",
    required: true,
    disabled: false,
    options: [
      { value: "available", label: "Disponible" },
      { value: "rented", label: "Loué" },
      { value: "maintenance", label: "En maintenance" },
    ],
  },
  {
    name: "contactPhone",
    fieldType: "phone",
    label: "Téléphone",
    required: true,
    disabled: false,
  },
];
