import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import RegisterDialog from "@/components/auth/RegisterDialog";
import LoginDialog from "@/components/auth/LoginDialog";
import ForgotPasswordDialog from "@/components/auth/ForgotPasswordDialog";
import QueryProvider from "@/context/query-provider";
import NextTopLoader from "nextjs-toploader";
import { Suspense } from "react";
import { ThemeProvider } from "@/components/theme-provider";
import NotificationSidebar from "@/components/NotificationSidebar";

export const metadata: Metadata = {
  title: "Auto Hunt",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` bg-card antialiased`}>
        <NextTopLoader color="#0000ff" />
        <QueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Suspense fallback={null}>
              <NuqsAdapter>
                <Suspense fallback={null}>
                  <RegisterDialog />
                  <LoginDialog />
                  <ForgotPasswordDialog />
                  <NotificationSidebar />
                </Suspense>
                <Suspense fallback={null}>{children}</Suspense>
              </NuqsAdapter>
            </Suspense>
          </ThemeProvider>
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
