import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import RegisterDialog from "@/components/auth/RegisterDialog";
import LoginDialog from "@/components/auth/LoginDialog";
import ForgotPasswordDialog from "@/components/auth/ForgotPasswordDialog";
import QueryProvider from "@/context/query-provider";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Auto Hunt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` bg-card antialiased`}>
        <NextTopLoader color="#0000ff" />
        <QueryProvider>
          <NuqsAdapter>
            <RegisterDialog />
            <LoginDialog />
            <ForgotPasswordDialog />
            {children}
          </NuqsAdapter>
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
