export const APP_CONFIG = {
  APPWRITE: {
    KEY: process.env.NEXT_APPWRITE_KEY!,
    ENDPOINT: process.env.APPWRITE_ENDPOINT!,
    PROJECT_ID: process.env.APPWRITE_PROJECT_ID!,
    DATABASE_ID: process.env.APPWRITE_DATABASE_ID!,

    CAR_LISTING_ID: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_CAR_LISTING_ID!,
    BUCKET_IMAGES_ID: process.env.NEXT_PUBLIC_APPWRITE_BUCKET_IMAGES_ID!,
    PUBLIC_ENDPOINT: process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!,
    PUBLIC_PROJECT_ID: process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!,
    PUBLIC_DATABASE_ID: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!,

    PUBLIC_CAR_LISTING_ID:
      process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_CAR_LISTING_ID!,
    PUBLIC_BUCKET_IMAGES_ID: process.env.NEXT_PUBLIC_APPWRITE_BUCKET_IMAGES_ID!,
  },
};
